### ISSUE TITLE
Enhancement: Allow input for exact size and rotation

### ISSUE THREAD

**Issue by Lopolin-LP** [akopachov/sveltab#15]
right now, once I for example rotate something, it's impossible to get it back to 0°. With this, this could be fixed, and I could also set it to be exactly 45° instead of... something that's roughly 45°. same for the size of an element, currently impossible to get the size exact.

**Comment by akopachov** [comment]
Great idea! Thank you

**Comment by akopachov** [comment]
Should be implemented in v2.3.0
