### ISSUE TITLE
Help: "Uncaught Error: effect_update_depth_exceeded" after trying to transform rotated element with exact measurements

### ISSUE THREAD

**Issue by Lopolin-LP** [akopachov/sveltab#17]
I added a new element (a clock), tried rotating the clock, then used the new exact sizing inputs to resize it, however it completely bugged out and after reloading the page it doesn't allow me to edit the page anymore, at all. It also states the following errors in the console:

15:32:49.738
Uncaught Error: effect_update_depth_exceeded
    Immutable 45
[utils.BVRBB_1P.js:1:971](moz-extension://9322e338-4e0e-4ab8-97e6-4c33d871c596/app/immutable/chunks/utils.BVRBB_1P.js)
15:32:49.758
Uncaught (in promise) Error: effect_update_depth_exceeded
    Immutable 9
[utils.BVRBB_1P.js:1:971](moz-extension://9322e338-4e0e-4ab8-97e6-4c33d871c596/app/immutable/chunks/utils.BVRBB_1P.js)

And the clock that's in the middle doesn't update anymore, until I refresh the page. So how do I remove the buggy element to perhaps try to figure out what's going on there?

Browser: Floorp 11.21.0 (Firefox 128.5.0)

**Comment by akopachov** [comment]
Hey, sorry to hear you experiencing this.

To be honest, I was not able to reproduce it on the latest FireFox 133. However, I did some code changes to make this piece better.

Until I publish a new release to the stores, feel free to give it a try [here](https://demo.sveltab.com/)

**Comment by Lopolin-LP** [comment]
> feel free to give it a try [here](https://demo.sveltab.com/)

oh I completely forgot that the demo site existed! I just experimented around and it turns out it's a completely different bug: When scaling the clock's height down to 16px or lower, then it freaks out. And it seems to be *only* the clock. What's interesting is that on latest Firefox it's able to "save itself" by reverting to a previous state when reloading the page, thus you can still use it... But not on Firefox 128 ESR...

**Comment by akopachov** [comment]
ah, managed to find the cause. Your investigation helped a lot.

Fixed version is available at https://demo.sveltab.com/

If no blockers or critical bugs, then I'm going to publish it to the store tomorrow
