### ISSUE TITLE
Add "Daily Bible verse" widget

### ISSUE THREAD

**Issue by akopachov** [akopachov/sveltab#19]
As suggested in #18

**Comment by akopachov** [comment]
This seems to be a good one - https://bible.helloao.org/docs/

**Comment by akopachov** [comment]
Making some progress here and for now I need some help to find which translation out of [1000+](https://bible.helloao.org/api/available_translations.json) should be set by default when widget is getting added to the workspace.

@El3ctricFX I feel like you understand this topic way better than I do, so may I kindly ask you for help here?

**Comment by El3ctricFX** [comment]
> Making some progress here and for now I need some help to find which translation out of [1000+](https://bible.helloao.org/api/available_translations.json) should be set by default when widget is getting added to the workspace.
> 
> @El3ctricFX I feel like you understand this topic way better than I do, so may I kindly ask you for help here?

Ya no problem and i understand, if possible use the NLT (New living Translation) 

https://crosswire.org/sword/index.jsp

Crosswire has a lot of good module resources if thats any help. And KJV Is under public domain so if thats easier then it works.

NLT is what i use and find is one of the easy while being a good overall translatation

**Comment by akopachov** [comment]
It looks like [the API](https://bible.helloao.org/) doesn't provide NLT (or probably named somehow else?). Here are the list of available translations for English language:

| name                                                      | shortName | website                                                     |
|-----------------------------------------------------------|-----------|-------------------------------------------------------------|
| Berean Standard Bible                                     | BSB       | https://berean.bible/                                       |
| World English Bible                                       | WEBP      | https://ebible.org/Scriptures/details.php?id=engwebp        |
| American Standard Version Byzantine Text                  | ABT       | https://ebible.org/Scriptures/details.php?id=engasvbt       |
| Anindilyakwa English Bible                                | AOI       | https://ebible.org/Scriptures/details.php?id=engaoi         |
| American Standard Version (1901)                          | ASV       | https://ebible.org/Scriptures/details.php?id=eng-asv        |
| Bible in Basic English                                    | BBE       | https://ebible.org/Scriptures/details.php?id=engBBE         |
| Brenton Septuagint Translation                            | BRE       | https://ebible.org/Scriptures/details.php?id=eng-Brenton    |
| Darby Translation                                         | DBY       | https://ebible.org/Scriptures/details.php?id=engDBY         |
| Douay-Rheims 1899                                         | DRV       | https://ebible.org/Scriptures/details.php?id=engDRA         |
| English Majority Text Version                             | EMTV      | https://ebible.org/Scriptures/details.php?id=engemtv        |
| The New Testament with Commentary                         | F35       | https://ebible.org/Scriptures/details.php?id=engf35         |
| Free Bible Version                                        | FBV       | https://ebible.org/Scriptures/details.php?id=engfbv         |
| God's Living Word                                         | GLW       | https://ebible.org/Scriptures/details.php?id=eng-glw        |
| Geneva Bible 1599                                         | GNV       | https://ebible.org/Scriptures/details.php?id=enggnv         |
| JPS TaNaKH 1917                                           | JPS       | https://ebible.org/Scriptures/details.php?id=engjps         |
| King James Version + Apocrypha                            | KJA       | https://ebible.org/Scriptures/details.php?id=eng-kjv        |
| King James (Authorized) Version                           | KJV       | https://ebible.org/Scriptures/details.php?id=eng-kjv2006    |
| Isaac Leeser Tanakh                                       | LEE       | https://ebible.org/Scriptures/details.php?id=englee         |
| Literal Standard Version                                  | LSV       | https://ebible.org/Scriptures/details.php?id=englsv         |
| LXX2012: Septuagint in British/International English 2012 | LXU       | https://ebible.org/Scriptures/details.php?id=eng-uk-lxx2012 |
| LXX2012: Septuagint in American English 2012              | LXX       | https://ebible.org/Scriptures/details.php?id=eng-lxx2012    |
| Nyangumarta English Bible                                 | NNA       | https://ebible.org/Scriptures/details.php?id=engnna         |
| George Noyes Bible                                        | NOY       | https://ebible.org/Scriptures/details.php?id=engnoy         |
| One Unity Resource Bible                                  | OUR       | https://ebible.org/Scriptures/details.php?id=engourb        |
| Plain English Version                                     | PEV       | https://ebible.org/Scriptures/details.php?id=engPEV         |
| Revised Version with Apocrypha (1895)                     | RV5       | https://ebible.org/Scriptures/details.php?id=eng-rv         |
| Translation for Translators                               | T4T       | https://ebible.org/Scriptures/details.php?id=eng-t4t        |
| Text-Critical English New Testament                       | TCE       | https://ebible.org/Scriptures/details.php?id=engtcent       |
| Tyndale New Testament                                     | TNT       | https://ebible.org/Scriptures/details.php?id=engtnt         |
| Unlocked Literal Bible                                    | ULB       | https://ebible.org/Scriptures/details.php?id=engULB         |
| Wycliffe Bible                                            | W88       | https://ebible.org/Scriptures/details.php?id=engWycliffe    |
| Noah Webster Bible                                        | WBS       | https://ebible.org/Scriptures/details.php?id=engwebster     |
| World English Bible with Deuterocanon                     | WEB       | https://ebible.org/Scriptures/details.php?id=eng-web        |
| World English Bible (Catholic)                            | WEBC      | https://ebible.org/Scriptures/details.php?id=eng-web-c      |
| World English Bible                                       | WEBP      | https://ebible.org/Scriptures/details.php?id=engwebp        |
| World English Bible British Edition                       | WEBPB     | https://ebible.org/Scriptures/details.php?id=engwebpb       |
| World English Bible British Edition with Deuterocanon     | WEU       | https://ebible.org/Scriptures/details.php?id=eng-webbe      |
| World Messianic Bible                                     | WMB       | https://ebible.org/Scriptures/details.php?id=engwmb         |
| World Messianic Bible British Edition                     | WMU       | https://ebible.org/Scriptures/details.php?id=engwmbb        |
| Wycliffe's Bible with Modern Spelling                     | WYC2017   | https://ebible.org/Scriptures/details.php?id=engwyc2017     |
| Wycliffe's Bible with Modern Spelling (Enhanced)          | WYC2018   | https://ebible.org/Scriptures/details.php?id=engwyc2018     |
| Young's Literal Translation                               | YLT       | https://ebible.org/Scriptures/details.php?id=engylt         |

**Comment by El3ctricFX** [comment]
All good, just put kjv (appreciate making it btw)

**Comment by akopachov** [comment]
Thank you for your input.

This is available now at [demo website](https://demo.sveltab.com/). Once make sure there are no obvious issues I'll push it to the store
